name: Deploy to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@main
      with:
        #Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: http://18.116.48.180:9000
        login: squ_9570b5325cb72147ae38b5823e991e0f6094ec68
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA6DEOILNOCPO4OC6L
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 968813468508.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: githubactions
        IMAGE_TAG: Test_Github_1.0.2
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
   - name: Send mail
       if: always()
       uses: Prasadfasi/GitHub-Actions/actions@v2
       with:
       server_address: smtp.gmail.com
       server_port: 465
       username: ${{ secrets.EMAIL_USERNAME }}
       password: ${{ secrets.EMAIL_PASSWORD }}
       subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
       body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
       to: fasireddygmail.com
       from: Prasad
    
